export const SNOWFLAKE_CALL_PLAN_STATEMENT = `SELECT OBJECT_CONSTRUCT(
  'SALES_SUPERVISOR_NIK', SALES_SUPERVISOR_NIK,
  'SALES_SUPERVISOR_NAME', MAX(SALES_SUPERVISOR_NAME),
  'DETAIL', ARRAY_AGG(OBJECT_CONSTRUCT(
    'SALES_NIK', SALES_NIK,
    'SALES_NAME', SALES_NAME,
    'CALL_PLAN_NUMBER', CALL_PLAN_NUMBER,
    'ROUTE_NUMBER', ROUTE_NUMBER,
    'CABANG', CABANG
  ))
) AS DATA
FROM DEV_SFA_OUTSYSTEMS.SFA.V_API_CALL_PLAN_V2
WHERE CALL_PLAN_START_DATE = ?
GROUP BY SALES_SUPERVISOR_NIK`;