import { MigrationInterface, QueryRunner } from "typeorm";

export class FixTimestamp1763949128594 implements MigrationInterface {
    name = 'FixTimestamp1763949128594'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "m_io" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_io" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_io" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_io" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_io" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_io" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "user_manage" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_manage" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_manage" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_manage" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_manage" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "user_manage" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_pallet" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_pallet" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_pallet" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_pallet" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_pallet" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_pallet" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_item" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_item" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_item" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "outbound_do" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_do" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_do" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_do" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_do" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_do" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "inbound_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_item" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_item" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_item" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "inbound_do" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_do" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound_do" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_do" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound_do" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_do" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "inbound" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inbound" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inbound" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inbound" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "approval_level" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "approval_level" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_level" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "approval_level" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_level" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "approval_level" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "approval_setup" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "approval_setup" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_setup" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "approval_setup" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_setup" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "approval_setup" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "approval" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "approval" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "approval" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "approval" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7934bceba4c8503e3d87e18eb6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65bb163f315f8bc642a706db6a"`);
        await queryRunner.query(`ALTER TABLE "notification_history" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notification_history" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification_history" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "notification_history" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification_history" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "notification_history" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_week" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_week" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_week" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_week" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_week" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_week" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "move_order_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "move_order_item" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "move_order_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "move_order_item" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "move_order_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "move_order_item" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "move_order" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "move_order" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "move_order" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "move_order" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "move_order" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "move_order" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_uom" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_uom" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_uom" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_uom" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_uom" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_uom" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_supplier" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_supplier" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_supplier" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_supplier" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_supplier" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_supplier" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "customer_main" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customer_main" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_main" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customer_main" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_main" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "customer_main" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`CREATE INDEX "IDX_7934bceba4c8503e3d87e18eb6" ON "notification_history" ("type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_65bb163f315f8bc642a706db6a" ON "notification_history" ("user_id", "created_at") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_65bb163f315f8bc642a706db6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7934bceba4c8503e3d87e18eb6"`);
        await queryRunner.query(`ALTER TABLE "customer_main" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "customer_main" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customer_main" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customer_main" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_main" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customer_main" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement_pallet" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_movement" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking_history" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "customer_subdist" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_classification_item" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_vehicle" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_supplier" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_supplier" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_supplier" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_supplier" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_supplier" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_supplier" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_uom" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_uom" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_uom" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_uom" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_uom" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_uom" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "move_order" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "move_order" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "move_order" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "move_order" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "move_order" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "move_order" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "move_order_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "move_order_item" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "move_order_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "move_order_item" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "move_order_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "move_order_item" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_week" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_week" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_week" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_week" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_week" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_week" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification_history" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "notification_history" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notification_history" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "notification_history" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification_history" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notification_history" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_65bb163f315f8bc642a706db6a" ON "notification_history" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7934bceba4c8503e3d87e18eb6" ON "notification_history" ("created_at", "type") `);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_put_away" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "stock_adjustment_approval" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "approval" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "approval" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "approval" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "approval" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_setup" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "approval_setup" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "approval_setup" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "approval_setup" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_setup" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "approval_setup" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_level" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "approval_level" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "approval_level" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "approval_level" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_level" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "approval_level" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_inbound" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inbound" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inbound" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inbound" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inbound" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_helper" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound_do" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_do" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inbound_do" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_do" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound_do" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_do" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_item" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inbound_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_item" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inbound_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inbound_item" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_scan_picking" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_picking" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_do" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_do" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "outbound_do" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_do" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_do" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_do" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assigned_picking" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "outbound_memo_item" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_item" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_item" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_item" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_item" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_bin" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory_tracking" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse_sub" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_pallet" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_pallet" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_pallet" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_pallet" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_pallet" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_pallet" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transaction_pallet_history" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_warehouse" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_manage" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "user_manage" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_manage" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_manage" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_manage" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_manage" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_details" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_details" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_io" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "m_io" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "m_io" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "m_io" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "m_io" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "m_io" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
    }

}
